GET http://localhost:5000/api/games

###

GET http://localhost:5000/api/users


### 
POST http://localhost:5000/api/signin
Content-Type: application/json

{
    "username":"test2",
    "password":"12345678"

}

### 
POST http://localhost:5000/api/signup
Content-Type: application/json

{
    "username":"test10",
    "password":"12345678"

}

###

GET http://localhost:5000/api/auth



### Fetch user lib
GET http://localhost:5000/api/library
Content-Type: application/json

{
  "userId": 6
}


### Search Games by Title
GET http://localhost:5000/api/games/search?title=C


### Search Games by Title
GET http://localhost:5000/api/users/search?title=C
### Fetch Most Sold Games
GET http://localhost:5000/api/games/most-sold

### filter by name
GET http://localhost:5000/api/games/name
Content-Type: application/json


### Get Comments for a Game
GET http://localhost:5000/api/games/1/comments

### Fetch Friend List
POST http://localhost:5000/api/friends/add
Content-Type: application/json

{
  "userId": "6",
  "friendId":"1"
}

###
GET http://localhost:5000/api/comments/user/6
Content-Type: application/json


###
GET http://localhost:5000/api/games/publisher/2
Content-Type: application/json



###
GET http://localhost:5000/api/users/1/common-games/4
Content-Type: application/json


###

GET http://localhost:5000/api/home/recommended
